### ISSUE TITLE
No se realizan los càlculos con SQL

### ISSUE THREAD

**Issue by lndl** [Titinx/Facturador_rails#2]
Si bien la lógica es correcta, està hecha directamente en Ruby, sin aprovechar la interfaz de Active Record para operar directamente sobre el motor de BDD. Con un volumen de datos real la aplicación sería demasiado lenta porque se realiza en el proceso Ruby y no se ejecuta ningun tipo de "filtro" en el marco de la base de datos.
Al margen de esto -que es muy importante- las operaciones quedaron bastante procedurales (se podría haber utilizado un #inject)

Por favor, mirà si podès reimplementar lo mismo que tenès -que es correcto- usando el ORM y pensando màs en SQL.

**Comment by Titinx** [comment]
Hola Nahuel, estuve solucionando algunos los problemas que me mencionaste, pero me surgieron algunas dudas por lo cual te mande un mail de consulta.

**Comment by lndl** [comment]
Sí, recién respondí tu mail.
Avisame cualquier cosa.
Saludos.

**Comment by lndl** [comment]
OK, este punto ha sido mejorado. Cierro el ticket.
